print("What is your name?")
name = input()
print("Hi " + name)
print("How long have you been coding " + name + "?")
time = input()
print("That is not so bad " + name + ". So you are telling me, that you have been coding " + time +"?. Nice!")
print("Thanks for chat " + name + ". And enjoy your coding.")
